// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9l76asJm56MVTD8Oed9jKw0vZYeVgAHM',
    appId: '1:822918700528:android:4e0ea13e5494872f245135',
    messagingSenderId: '822918700528',
    projectId: 'iwash-d6737',
    databaseURL: 'https://iwash-d6737-default-rtdb.firebaseio.com',
    storageBucket: 'iwash-d6737.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtbgwhZ6obvpvlflDzdNngTT7mxq7dNew',
    appId: '1:822918700528:ios:739c67264ee1a309245135',
    messagingSenderId: '822918700528',
    projectId: 'iwash-d6737',
    databaseURL: 'https://iwash-d6737-default-rtdb.firebaseio.com',
    storageBucket: 'iwash-d6737.appspot.com',
    androidClientId:
        '822918700528-v2sptvr253kjqbv8bud96m2lctirsq3g.apps.googleusercontent.com',
    iosClientId:
        '822918700528-535b4u3tjnsis9fv5gksepkq8qb2605g.apps.googleusercontent.com',
    iosBundleId: 'com.example.iwash',
  );
}
